ASP.NET Core MVC/First_AspNetCoreMVC/Components/RegistrationListViewComponent.cs
using First_AspNetCoreMVC.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Microsoft.Win32;

namespace First_AspNetCoreMVC.Components
{
    public class RegistrationListViewComponent: ViewComponent
    {

        //private IDataService _dataService;
        //private IConfigurationRoot _config;
        private IOptions<RegistrationConfig> _regConfig;
        private ILogger<RegistrationListViewComponent> _logger;
        private DemoContext _dbContext;

        // Changed IDataService to DemoContext
        public RegistrationListViewComponent(DemoContext dbContext, IOptions<RegistrationConfig> regConfig, ILogger<RegistrationListViewComponent> logger)
        {
            this._dbContext = dbContext;
            //this._dataService = dataService;
            this._regConfig = regConfig;
            this._logger = logger;
        }

        //public RegistrationListViewComponent(IDataService dataService, IOptions<RegistrationConfig> regConfig, ILogger<RegistrationListViewComponent> logger)
        //{
        //    this._dataService = dataService;
        //    this._regConfig = regConfig;
        //    this._logger = logger;
        //}

        //public RegistrationListViewComponent(IDataService dataService)
        //{
        //    this._dataService = dataService;

        //}

        public async Task<IViewComponentResult> InvokeAsync()
        {
            this._logger.LogInformation($"Invoking {nameof(RegistrationListViewComponent)}");

            var registrations = await this._dbContext.Registrations.ToListAsync();
            //var registrations = await this._dataService.GetRegistrations();

            //var pageSize = _regConfig.GetValue<int?>("RegistrationList:PageSize")?? 25;
            var pageSize = _regConfig.Value.PageSize;

            this._logger.LogInformation($"Exiting InvokeAsync of {nameof(RegistrationListViewComponent)}");

            return View(registrations.Take(pageSize));

            //return View(registrations);
        }    
    }
}

ASP.NET Core MVC/First_AspNetCoreMVC/Controllers/DemoController.cs
using Microsoft.AspNetCore.Mvc;
using First_AspNetCoreMVC.Models;
using First_AspNetCoreMVC.Data;

namespace First_AspNetCoreMVC.Controllers
{
    public class DemoController : Controller
    {
        private DemoContext _dbContext;

        public IActionResult Index()
        {
            return View();
        }

        public DemoController(DemoContext dbContext)
        {
            this._dbContext = dbContext;
        }

        //[HttpGet]
        //public IActionResult Register()
        //{
        //    return View();
        //}

        [HttpGet]
        public IActionResult Register(int? id)
        {
            if (id.HasValue)
            {
                var reg = _dbContext.Registrations.SingleOrDefault(r => r.Id == id);
                if (reg != null)
                    return View(reg);
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id.HasValue)
            {
                var reg = _dbContext.Registrations.SingleOrDefault(r => r.Id == id);
                if (reg != null)
                {
                    _dbContext.Registrations.Remove(reg);

                    await _dbContext.SaveChangesAsync();
                    return View(nameof(Index));
                }
            }

            return View(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegistrationModel model, string action)
        {
            var reg = _dbContext.Registrations.Find(model.Id);

            switch (action)
            {
                case "Register":
                    // Handle edit logic here
                    if (ModelState.IsValid)
                    {
                        if (model.Id == 0)  // A new record
                        {
                            _dbContext.Registrations.Add(model);
                        }
                        else  // An existing record to update
                        {                            
                            reg.Email = model.Email;
                            reg.FirstName = model.FirstName;
                            reg.LastName = model.LastName;
                        }

                        await _dbContext.SaveChangesAsync();
                        return View(nameof(Index));
                    }
                    break;
                case "Delete":
                    // Handle delete logic here
                    
                    if (reg != null)
                    {
                        _dbContext.Registrations.Remove(reg);

                        await _dbContext.SaveChangesAsync();
                        return View(nameof(Index));
                    }
                    
                    break;
            }
            //return RedirectToAction("Index");



            //if (ModelState.IsValid)
            //{
            //    if (model.Id == 0)  // A new record
            //    {
            //        _dbContext.Registrations.Add(model);
            //    }
            //    else  // An existing record to update
            //    {
            //        var reg = _dbContext.Registrations.Find(model.Id);
            //        reg.Email = model.Email;
            //        reg.FirstName = model.FirstName;
            //        reg.LastName = model.LastName;
            //    }

            //    await _dbContext.SaveChangesAsync();
            //    return View(nameof(Index));
            //}
            return View();
        }

        

        //[HttpDelete]
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    var reg = _dbContext.Registrations.Find(id);
        //    if (reg != null)
        //    {
        //        _dbContext.Registrations.Remove(reg);                

        //        await _dbContext.SaveChangesAsync();
        //        return View(nameof(Index));
        //    }

        //    return View();
        //}
    }
}

ASP.NET Core MVC/First_AspNetCoreMVC/Views/Demo/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Demo Index Page";
}

@await Component.InvokeAsync("RegistrationList")

ASP.NET Core MVC/First_AspNetCoreMVC/Views/Demo/Register.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model RegistrationModel
@{
    ViewData["Title"] = "Form";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        <h4>Registration Form</h4>
    </div>
    <div>
        <h4><a asp-controller="Demo" asp-action="Index">&lt; Back</a></h4>
    </div>
    <div class="panel-body">
        <form asp-controller="Demo" asp-action="Register" method="POST">
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <div>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group" style="margin-top:10px">
                <label asp-for="LastName" class="control-label"></label>
                <div>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group" style="margin-top:10px">
                <label asp-for="Email" class="control-label"></label>
                <div>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group" style="margin-top:10px">
                <button asp- class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</div>